### ISSUE TITLE
Navmesh is not generated/updated sometimes

### ISSUE THREAD

**Issue by nightactive-git** [TheGrimsey/oxidized_navigation#10]
I noticed that the navmesh is sometimes not generated. Here is a screenshot:
<img width="772" alt="navmesh_generation_issue" src="https://github.com/TheGrimsey/oxidized_navigation/assets/70406722/b79d5dae-ccfc-45a2-a1e9-2f68f24fc81f">
I place red blocks on a green plane. In the screenshot above we see that the navmesh is constructed on top of the red box but the navmesh on the green plane is not updated.

The behavior is very inconsistent, because sometimes it is generated correctly. I also noticed, that blocks that are placed on two tiles sometimes generate/update the navmesh for only one tile:
<img width="672" alt="problem_with_navmesh_genration" src="https://github.com/TheGrimsey/oxidized_navigation/assets/70406722/774a5921-a188-457b-b81f-1e014899659c">

**Comment by TheGrimsey** [comment]
Hmmm.

Could you share your NavMeshGeneration settings, plugin & bevy versions, etc? 

This isn't much to go on at present.

**Comment by nightactive-git** [comment]
yes for sure. 
Here are my **dependencies**:
bevy = { version = "0.10.0", features = ["dynamic_linking"] }
rand = "0.8.5"
bevy_mod_raycast = "0.8.0"
oxidized_navigation = "0.4.0"
bevy_prototype_debug_lines = { version = "0.10", features = ["3d"] }
bevy_rapier3d = "0.21.0"
futures-lite = "1.13.0"

and these are my **plugin settings**:
cell_width: 0.2,
            cell_height: 0.1,
            tile_width: 100,
            world_half_extents: 250.0,
            world_bottom_bound: -100.0,
            max_traversable_slope_radians: (40.0_f32 - 0.1).to_radians(),
            walkable_height: 20,
            walkable_radius: 2,
            step_height: 16,
            min_region_area: 50,
            merge_region_area: 500,
            max_contour_simplification_error: 1.1,
            max_edge_length: 80,

At the moment I'm experimenting with these settings. But the issue is re-producable with those settings every time.

**Comment by TheGrimsey** [comment]
Sorry for being so slow to come back to this.

My guess is that this has to do with your ``step_height`` being very high as this causes the nav-mesh to link points together.

I might be able to make some minor changes to improve this, but I would recommend looking over if 16 is the right step height for you.

**Comment by nightactive-git** [comment]
Hi Grim, 
tanks for your reply and support. I did some testing with the step_height. I reduced it to one, but that didn't help. Then I started to increase the step_height. It got a bit better when I reached 8, but there were still problems.
Now I increased the walkable_height to 40 (two times the character height) and now the problem is gone. I assume that the area IN the cube got identified as walkable and then it got combined sometimes with the walkable area outside the cube.

In another thread I red, that you plan to introduce negative volumes. Is this still on your roadmap?

Kind regards!

**Comment by TheGrimsey** [comment]
> I assume that the area IN the cube got identified as walkable and then it got combined sometimes with the walkable area outside the cube.

That is possible if your scale allows it. Hmmm, likely a nicer way to solve this by 'filling' the interior of the cube as well.

> In another thread I red, that you plan to introduce negative volumes. Is this still on your roadmap?

Yes, it is. I simply need to figure out a nice way to handle volumes as a whole.

**Comment by TheGrimsey** [comment]
This should have been fixed by 0.5.2 a few days ago, please reopen if it is still an issue.
