### ISSUE TITLE
2D support

### ISSUE THREAD

**Issue by musjj** [TheGrimsey/oxidized_navigation#17]
Would it be possible to support support 2D colliders (`bevy_xpbd_2d`, etc.)? From what I've seen, it should be technically possible to generate navigation meshes for 2D stuff.

**Comment by TheGrimsey** [comment]
Maybe but _it's not on my to-do list._

It's not quite the same problem. Many things that apply to 3D **don't** apply to 2D.

It'd probably be easier to make a completely separate crate for it.
