### ISSUE TITLE
Navmesh is generated inconsistently at the edges of tiles

### ISSUE THREAD

**Issue by janhohenheim** [TheGrimsey/oxidized_navigation#2]
See minimal example of bug at https://github.com/janhohenheim/navigation-mcve
- [Discord discussion](https://discord.com/channels/691052431525675048/1064621333234843790/1065290861753139232)
- The red debug line tries to navigate from inside the house to the camera, but does so while erroneously going through walls:
![image](https://user-images.githubusercontent.com/9047632/213222087-7ea0b247-c5bd-4572-9491-3f860187cd3e.png)

Inconsistent generation:
![image](https://user-images.githubusercontent.com/9047632/213220574-d38f0c5a-2c55-4ec7-8c81-e342eafa01e0.png)
![image](https://user-images.githubusercontent.com/9047632/213220607-ee6b2883-b887-4b29-a40b-4363ec16be39.png)

**Comment by TheGrimsey** [comment]
In 0.2 this is mitigated when ``walkable_radius > 0`` (the tile is temporarily extended during generation to correctly handle radius outside of a single tile).

Not closing this yet though. I have a solution for when ``walkable_radius == 0`` which I will get around to.

**Comment by janhohenheim** [comment]
Nice! As soon as you have the fix, I'll try incorporating it again into [foxtrot](https://github.com/janhohenheim/foxtrot).

**Comment by janhohenheim** [comment]
Update: I already added it to Foxtrot on the `main` branch. It works soooo much better than before, thanks! It still sometimes tries to find a path directly through a building and other times takes a detour even though the target is within line of sight. I added a little condition that if line of sight is established, pathfinding is halted and the NPC just goes directly in my direction. With that change, the shortcomings are barely noticeable, so I'm already quite happy!. 
Do you have any advice for params to further tweak? I am still using the same params as your example.

**Comment by janhohenheim** [comment]
After playing a bit with the settings, I found that the reason behind the pathfinding taking long ways is that I set the walkable radius too high, thus making it impossible to take the short paths which were narrower. So ignore that part of my comment :)

**Comment by TheGrimsey** [comment]
_I've been forgetting to respond to this. Sorry for that._

I'm gonna pull Foxtrot and see if I can figure it out. Looks to be an excellent example of a slightly more complex scene. Might be I've made an error in the voxelization somewhere.

**Comment by janhohenheim** [comment]
No problem 😄 
I've changed the navmesh generation settings a bit to minimize the issues, but sometimes a path through a wall is still generated. It's hard to reproduce though. 
To show the navmesh and pathfinding ingame press Q to free the mouse, click on "Open window" on the top of the screen, select "Foxtrot Dev" and then enable "Navmeshes".:
![image](https://user-images.githubusercontent.com/9047632/220752736-ccb7a385-f33c-4572-b923-3bbf188dd409.png)

**Comment by TheGrimsey** [comment]
Sorry for being so late getting back to this. 

I don't know if it's something you've changed or something that happened in relation to 0.10 but pulling the latest version of Foxtrot, and having a wander around, I couldn't see any points where it looks like the Nav-mesh is incorrectly connecting.

This was on the default ``old_town`` map.

_I see some need for improvements on my end though, I'm not a fan of how the generation creates inaccessible islands inside buildings. I would like to add a 'negative' volume to remove those._

**Comment by nightactive-git** [comment]
Hi,
I'm not sure if my topic is related to this one, but I also noticed a problem with navmesh generation if an object intersect two tiles. I have a plane and place Blocks on it. Sometimes only the half of the block is regarded on the plane. Here is a screenshot:
<img width="672" alt="problem_with_navmesh_genration" src="https://github.com/TheGrimsey/oxidized_navigation/assets/70406722/aaede3bd-1b68-4b6a-8ca1-d12ccd8625b1">

**Comment by TheGrimsey** [comment]
I believe this should've been fixed in 0.5.2 released a few days ago. Would love to hear if you still see this issue, otherwise, I am closing this for now.

**Comment by janhohenheim** [comment]
Cool! I'll check when I port Foxtrot to 0.11 :)
