### ISSUE TITLE
Multi-level nav meshes?

### ISSUE THREAD

**Issue by 0xh007** [TheGrimsey/oxidized_navigation#20]
I'm currently working on a project in Bevy +XPBD and am trying to utilize this crate for navigation. I have two box colliders representing two levels of a structure - like a multi-story building. The second box collider is positioned 20 units above the first one. I am adding nav mesh affectors to each of them. I can easily get a nav mesh to generate for the bottom structure, or the top structure if I increase the cell_height, but not both. I am planning to eventually connect the levels with a type of portal mechanism (ladder). 

I noticed this in the todos: 
`Nav-mesh "layers" using different NavMeshSettings.`

Would my use case be applicable to this or am I missing something simple?

Relevant Code:
Navmesh Plugin Setup - https://github.com/0xh007/empire_of_wind/blob/ai/src/plugins/navmesh.rs
Environment building - https://github.com/0xh007/empire_of_wind/blob/ai/src/plugins/ship_builder.rs

**Comment by TheGrimsey** [comment]
You've discovered a bug 😅I will have a patch out in a few hours.

Layers are not meant for that, they are meant for when you have nav-mesh agents of different sizes.

**Comment by TheGrimsey** [comment]
Version 0.8.1 is now out. It should fix the issue. Thanks for the report.

Reopen if it persists.
