### ISSUE TITLE
Simplify setup of `NavMeshSettings`

### ISSUE THREAD

**Issue by Shatur** [TheGrimsey/oxidized_navigation#23]
[Here](https://github.com/projectharmonia/project_harmonia/blob/58296836497282884b2e19498829733da782fd61/src/main.rs#L64-L77) is how I currently have it set up in my game.

However, I believe we can simplify this process by setting some of the values based on game constants. Therefore, I propose providing a convenient constructor where you can pass your character and world parameters, and it will generate the struct with reasonable defaults. Additionally, we can include builder methods to allow for further customization of these defaults.

**Comment by TheGrimsey** [comment]
I am adding a [function for this](https://github.com/TheGrimsey/oxidized_navigation/blob/master/src/lib.rs#L280) in 0.11.

Do you think this satisfies? Is there anything else I've missed?

**Comment by Shatur** [comment]
Looks good to me!

**Comment by Shatur** [comment]
I think we can close the issue since the feature already in `master`.

**Comment by Shatur** [comment]
I tried it, but I need to adjust `walkable_radius`. Could you add a `with_*` method for it as well?

**Comment by TheGrimsey** [comment]
Bit late getting back to this but I've added a function for this.

**Comment by Shatur** [comment]
Thanks, just what I needed!
