### ISSUE TITLE
Update to Bevy 0.14

### ISSUE THREAD

**Issue by HeavyBro1337** [TheGrimsey/oxidized_navigation#27]
Hello, Bevy 0.14 has recently came out. Any plans on upgrading this crate any time soon?

Thanks in advance!

Ivan Korchmit

**Comment by TheGrimsey** [comment]
Yes!

I am simply waiting for bevy_rapier to update. Which they will hopefully do by Monday or Tuesday.

**Comment by andriyDev** [comment]
`bevy_rapier` has been updated to Bevy 0.14! :)

**Comment by TheGrimsey** [comment]
Sorry for the delay, v0.11 supporting Bevy 0.14 is now out!
