### ISSUE TITLE
Update to Bevy 0.10

### ISSUE THREAD

**Issue by janhohenheim** [TheGrimsey/oxidized_navigation#3]
Seeing as Bevy 0.10 is about to be released, I thought it's time to put this in the room 🙂

**Comment by TheGrimsey** [comment]
On my end it seems to be a very simple update, only requiring changes to adding the systems.

Now it is just to wait for bevy_rapier to update & maybe figure out how to set a default state now that you seemingly can't initialize with one.

**Comment by TheGrimsey** [comment]
T'is done! 0.3.0 is now out on crates.io!
