### ISSUE TITLE
Navmesh is not updated when an entity with `NavMeshAffector` is despawned

### ISSUE THREAD

**Issue by tim-blackbird** [TheGrimsey/oxidized_navigation#5]
[`RemovedComponents`](https://docs.rs/bevy/latest/bevy/ecs/removal_detection/struct.RemovedComponents.html) could be used to detect this.

**Comment by TheGrimsey** [comment]
Didn't mean to close this but apparently github does it automatically if you reference an issue in a commit.

Fix will be released tomorrow likely.

**Comment by TheGrimsey** [comment]
Addressed in 0.4.0! 🎉
