### ISSUE TITLE
Provide a single function to generate path

### ISSUE THREAD

**Issue by Shatur** [TheGrimsey/oxidized_navigation#6]
Currently user have to call [find_path](https://docs.rs/oxidized_navigation/0.4.0/oxidized_navigation/query/fn.find_path.html) and then [perform_string_pulling_on_path](https://docs.rs/oxidized_navigation/0.4.0/oxidized_navigation/query/fn.perform_string_pulling_on_path.html). It would be great to have a short helper that calls them both in case user need only path of polygons.

**Comment by TheGrimsey** [comment]
Will be added to the next release 👌
