### ISSUE TITLE
Pass settings to the plugin itself

### ISSUE THREAD

**Issue by Shatur** [TheGrimsey/oxidized_navigation#7]
The plugin won't work without initialized `NavMeshSettings`. So I would suggest to pass the settings directly into plugin as Bevy do for its plugin. This way user never forget to initialize it.

**Comment by Shatur** [comment]
And I would suggest to store the settings inside the `NavMesh` to avoid cloning it every time to pass it to `find_path`.

**Comment by TheGrimsey** [comment]
I've added a ``settings`` field to ``OxidizedNavigationPlugin``.

Have not yet addressed the secondary suggestion though I will consider it.

**Comment by Shatur** [comment]
Great, thank you!

The idea of the secondary suggestion is also purely for ergonomics. To avoid having an extra system parameter with settings to and reduce the number of arguments of `find_path`.

**Comment by TheGrimsey** [comment]
As of 0.5 you are required to pass a ``NavMeshSettings`` when adding the plugin.
